package ExecptionHandling;

// causing a exception deliberately 

public class causeException{
  
	public static void main(String[] args) throws ArithmeticException
	{
		// arithmetic exception 
		// fall under runtime exception
		// unchecked 
		
		System.out.println("Runing");
		
		int x = 100/0;
		System.out.println(x);
		
		
		System.out.println("Hello");
		
		
		// Null pointer exception 
		
	    /*String a = null;
	    System.out.println(a.charAt(0));
		*/
		
		
		
	}
	
	
}